spring:
    profiles:
        include:
        - common
    rabbitmq:
      host: 192.168.0.8
      username: admin
      password: admin

    datasource:
      url: jdbc:postgresql://192.168.0.9:5432/hello_spring_db
      username: keo
      password: ab1664!1
      driver-class-name: org.postgresql.Driver