spring:
  datasource:
    url: jdbc:postgresql://192.168.1.6:5432/test
    username: ncpadmin
    password: ncpadmin
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      hibernate:
      SQL: debug
      descriptor:
        sql: trace