spring:
  application:
    name: hello-spring
  datasource:
    url: jdbc:postgresql://223.130.151.160:5432/hello_spring_db
    username: keo
    password: ab1664!1
    driver-class-name: org.postgresql.Driver
logging:
  level:
    root: INFO
    reactor.netty.http.client: DEBUG
external:
  api:
    accessKey: QOSYncpev8FDqSQxQSNP
    secretKey: w1aLWlSD1o4FwWc8bwof6XFMbrbhfN2B1vOiG7CH