spring:
  application:
    name: hello-spring
logging:
  level:
    root: INFO
    reactor.netty.http.client: DEBUG
external:
  api:
    accessKey: QOSYncpev8FDqSQxQSNP
    secretKey: w1aLWlSD1o4FwWc8bwof6XFMbrbhfN2B1vOiG7CH