spring:
    profiles:
        include:
        - common
    rabbitmq:
        host: 223.130.140.56
        username: admin
        password: admin

    datasource:
        url: jdbc:postgresql://223.130.151.160:5432/hello_spring_db
        username: keo
        password: ab1664!1
        driver-class-name: org.postgresql.Driver